
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: family_user
      POSTGRES_PASSWORD: family_password
      POSTGRES_DB: family_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U family_user -d family_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://family_user:family_password@db/family_db
    command: uv run alembic upgrade head
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql+asyncpg://family_user:family_password@db/family_db
      REDIS_URL: redis://redis:6379
      SECRET_KEY: supersecretkey_change_me
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully
    volumes:
      - ./app:/app/app   # для hot-reload при разработке (опционально)
      - ./alembic:/app/alembic


volumes:
  postgres_data:
  redis_data: