[project]
name = "home-task"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nikul1n", email = "nikul1n@bk.ru" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "asyncpg>=0.31.0",
    "fastapi[standard]>=0.141.1",
    "gunicorn>=26.0.0",
    "httpx>=0.28.1",
    "psycopg2-binary>=2.9.12",
    "pydantic-settings>=2.15.0",
    "redis[hiredis]>=8.1.0",
    "sqlalchemy[asyncio]>=2.0.52",
    "uvicorn[standard]>=0.52.3",
]

[project.scripts]
home-task = "home_task:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
