@baseUrl = http://localhost:8000
# @name login
POST {{baseUrl}}/api/v1/auth/login/
Content-Type: application/json

# username={{$dotenv TEST_EMAIL}}&password={{$dotenv TEST_PASSWORD}}
{
    "email": "{{$dotenv TEST_EMAIL}}",
    "password": "{{$dotenv TEST_PASSWORD}}"
}

###

# @name register
POST {{baseUrl}}/api/v1/auth/registration
Content-Type: application/json

{
    "name": "Vasya",
    "email": "{{$dotenv TEST_EMAIL}}",
    "phone": "+79999999999",
    "birthday": "2000-12-22",
    "timezone": "+03",
    "password": "{{$dotenv TEST_PASSWORD}}"
}


# Header name must be a valid HTTP token 
# прописать данные которые приходят в usercreate